### ISSUE TITLE
Tooling Fail: mods to espressif SDK required for building

### ISSUE THREAD

**Issue by seclorum** [magicshifter/MS3000#11]
At the moment, to build MS3KOS you must do the following braindead things:

 _1_  // comment out the min() and max() macro's from Arduino.h.  This is braindead of Arduino to do these macro's, but so be it - developer beware!

`vi ~/.platformio/packages/framework-arduinoespressif/cores/esp8266/Arduino.h`

line #253 .. 254 should look like this- i.e. commented out:

`#ifndef _GLIBCXX_VECTOR
// arduino is not compatible with std::vector
//#define min(a,b) ((a)<(b)?(a):(b))

//#define max(a,b) ((a)>(b)?(a):(b))
# endif

`

(Please note: these macro's are buggy, do not use them!  Ever!)

Note: you must do 'make clean' after this, to rebuild the .pioenvs build-dir!

_2_  _isSpiffsFilenameValid_
At the moment, we use the SPIFFS openDir API inappropriately.  For that reason, stick a return 0 in the isSpiffsFilenameValid method, thus:

`vi ~/.platformio/packages/framework-arduinoespressif/cores/esp8266/spiffs_api.cpp`

`
bool isSpiffsFilenameValid(const char* name)
{
return true;
`
We will address the inappropriate filesystem usage in a separate issue.

Note: you _also_ must do 'make clean' after this, to rebuild the .pioenvs build-dir!  In fact, just generally, always do a clean build .. i.e. "make clean test monitor" ..

**Comment by seclorum** [comment]
SPIFFS issue has been treated as a BUG by upstream and the fix will be available shortly:

https://github.com/esp8266/Arduino/issues/1818

**Comment by wizard23** [comment]
I didn't follow this closely. Is this still an issue with the new toolchain?

**Comment by seclorum** [comment]
No longer an issue with new toolchain/espressif package.
