### ISSUE TITLE
Connection Issue in 1.2.0 release

### ISSUE THREAD

**Issue by s00500** [magicshifter/MS3000#13]
I tried that several times now... when I flash the 1.2.0 bin using the writeFirmware script the shifter does as it should but when I try to access the webinterface it stops to do anything and the interface is never fully loaded... tried 1.0.0 and everything is working again...

**Comment by cavac** [comment]
Have the same problem here with 2 shifters.

1.0.0 has (mostly) working WiFi. But on 1.2.0 it just doesn't work at all.

**Comment by gitratte** [comment]
i have the same problem with the 1.2.0 fw, but no 1.0.0 fw to go back to. 
can someone add a precompiled 1.0.0 firmware image to the downloads please.

**Comment by wizard23** [comment]
You can get V1.0 here https://github.com/magicshifter/MS3000/releases/tag/v1.0

**Comment by speendo** [comment]
Same problem here with V 1.9.1

was this ever resolved?

**Comment by wizard23** [comment]
Pleasue use the new monorepo here: https://github.com/magicshifter/MS4000
