### ISSUE TITLE
Missing WPA support in WiFi client mode

### ISSUE THREAD

**Issue by cavac** [magicshifter/MS3000#16]
It seems the shifters only accept non-encrypted connections when connecting to an access point. This makes WiFi pretty much useless[*] and is a severe restriction when planning to run multiple shifters.

I can only test in 1.0.0, because on 1.2.0 Wifi doesn't work at all.

[*] I don't even WANT to even start to consider running my home network unsecured...

**Comment by seclorum** [comment]
This is a documentation issue - you can of course connect the MS3000 to a password-protected Access Point - this is mostly visible through the admin.html interface.  However this needs to be better documented and also: is addressed better in the MS3KOS2.0 Web Interface features.

**Comment by wizard23** [comment]
Pleasue use the new monorepo here: https://github.com/magicshifter/MS4000
