### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by blablabla0815** [magicshifter/MS3000#17]
Hello.
I got my MicroShifter last week and the Usermanual is good.
I have problems to connect the pc to the Microshifter. Android 6 Device work after some trouble but I could only open the UserInterface with my PC (OK, old one with XP).

Some questions:
How can I delete images from the MagicShifter?
How can I backup Images?
What's that userImage.magicBitmap (dowladable with UserInterface).
The admin setup: Where can I give a Wifi-Password?

Thanks!
Roland

**Comment by seclorum** [comment]
>How can I delete images from the MagicShifter?


You can delete images by going to the shifters admin.html interface.  For example, if your shifter is named "blablabla.local", going to "blahblahblah.local/admin.html" using a web browser gives you a simplified administrative interface with access to the files stored on the MS3000.

>How can I backup Images?
 
See above.

>What's that userImage.magicBitmap (dowladable with UserInterface).

This is the name of the file that the Web Interface uses to store the image you have painted using the Image painter.  It always gets overwritten with the last-uploaded image you've edited, unless you give that image a special name (see the interface).  

>The admin setup: Where can I give a Wifi-Password?

See above details about admin.html.  


This will all be consolidated in the new MS3KOS2.0 Web Interface, btw.
