### ISSUE TITLE
1.9 Release please

### ISSUE THREAD

**Issue by wizard23** [magicshifter/MS3000#31]
It would be really awesome to make a new release NOW, JUST AS IT IS. Please release often release early ;)

**Comment by wizard23** [comment]
problem is that 1.3 is not availale and there are some issues with 1.2 which is what most people have...

**Comment by seclorum** [comment]
Righto, will prep it and work on this issue as top priority ..

**Comment by wizard23** [comment]
awesome :) 👍 🥇

**Comment by wizard23** [comment]
what's blocking us from doing this NOW? I promised so many people for the Congress...

**Comment by seclorum** [comment]
We need to integrate the new web interface with the filesystem - not so difficult - and then test everything and smooth out the edges of the new interface in case there are any.  But generally I see no reason we can't do this today at our next session .. will call  you when I'm on the way to the studio.

**Comment by wizard23** [comment]
Why? Just take a 1.2 shifter make it dump it and upload 1.666beta ;)

**Comment by wizard23** [comment]
Webinterface Not as important as otr!

**Comment by wizard23** [comment]
When can we have a 1.9 as is on https://github.com/magicshifter/MS3000/releases ?

**Comment by wizard23** [comment]
What's the status on that...I havce to flash 10 shifters for webshop...I'll try to build this myself now but it would be realy awesome to just have a working copy :)

**Comment by seclorum** [comment]
Done: https://github.com/magicshifter/MS3000/releases/tag/1.9.0

Features: Saves last-mode-in-use, new over-the-air (wifi) firmware UPDATE method, numerous bug fixes, refactor for 2.0.

Also, 15 new MS3000's have been flashed with 1.9.0 for the webshop.

**Comment by wizard23** [comment]
Most excellent, this can be used as a base for all future OTA firmwares :) :+1:

**Comment by wizard23** [comment]
In the https://github.com/magicshifter/MS3000/releases/tag/1.9.0 klink there is no .bin file attached...

**Comment by seclorum** [comment]
Fixed, closing.  (The upload hadn't completed.)
