### ISSUE TITLE
Save last-used mode.

### ISSUE THREAD

**Issue by seclorum** [magicshifter/MS3000#32]
We should save the last-used mode and restore to it after boot up.

**Comment by s00500** [comment]
This makes perfect sense!

**Comment by wizard23** [comment]
👍 The old shifter had this feature already ;)

**Comment by seclorum** [comment]
Fixed as of https://github.com/magicshifter/MS3000-Firmware/commit/0d5cbb8b58d9a502a130c0744c0be1021046173c

**Comment by wizard23** [comment]
🥇 👍

**Comment by seclorum** [comment]
Closing - fixed and working in 1.9.0 release.
