### ISSUE TITLE
Version 1.9.1: crash when device is connected via WiFi

### ISSUE THREAD

**Issue by speendo** [magicshifter/MS3000#33]
I flashed two Magic Shifter 3000 with version 1.9.1 yesterday. Everything is working fine until I try to connect another device via WiFi. 

The very moment when the device is connected, the LEDs on the MS freeze and it is no more responding to any of the three buttons (reset and power off buttons still work of course).

Also the webpage on https://192.168.4.1 is not loading.

The only way to get the device back "online" is a restart.

I'm new to the MS3000 so I cannot completely rule out that I made something wrong though.

**Comment by wizard23** [comment]
we are starving the WiFi atm. We are working on that atm.

**Comment by wizard23** [comment]
This should be fixed now! :)
Please use the new monorepo here: https://github.com/magicshifter/MS4000
