### ISSUE TITLE
build process fails

### ISSUE THREAD

**Issue by ffppmm** [magicshifter/MS3000#8]
Hi,

current master branch fails to build with the following error message:

> Submodule path 'MS3000-Firmware': checked out 'a3209033e5c4dffc534413e302a320ebdc528d9e'
> fatal: no submodule mapping found in .gitmodules for path 'Tools/esptool-ck'
> Failed to recurse into submodule path 'MS3000-Firmware'
> Makefile:17: recipe for target 'MS3000-Assets/README.md' failed
> make: **\* [MS3000-Assets/README.md] Error 128

I wonder why we need the Tools dir?

Build environment:

> Ubuntu 16.04
> GNU Make 4.1
> git version 2.7.4
> PlatformIO, version 2.9.1
> NodeJS v5.11.1

**Comment by ffppmm** [comment]
I changed the target:

> MS3000-Assets/README.md MS3000-Firmware/README.md MS3000-WebInterface/README.md:
>     git submodule init && git submodule update --recursive --remote
>     git submodule foreach git checkout master

To just update the submodules:

> MS3000-Assets/README.md MS3000-Firmware/README.md MS3000-WebInterface/README.md:
>     git submodule init && git submodule update

I will create a pull request if you like

**Comment by seclorum** [comment]
Yeah, thats no longer necessary.  A PR would be cool.

**Comment by wizard23** [comment]
@seclorum Is this fixed now?

**Comment by seclorum** [comment]
TODO: confirm this is fixed.

**Comment by wizard23** [comment]
Pleasue use the new monorepo here: https://github.com/magicshifter/MS4000
