### ISSUE TITLE
make modules fails

### ISSUE THREAD

**Issue by ffppmm** [magicshifter/MS3000#9]
Hi,

after resolving the Problem with #8 the build of the firmware fails:

> make[2]: Entering directory '/home/XXX/MS3000_TEST/MS3000-Firmware/MS3KOS'
> pio run -p `pio serialports list --json-output | python -c 'exec("""\nimport json,sys\n\nobj=json.load(sys.stdin)\nfor y in obj:\n if "10C4:EA60" in y["hwid"]:\n  print y["port"]\n""")'`
> Error: no such option: -p
> Makefile:5: recipe for target 'run' failed
> make[2]: **\* [run] Error 2

Build environment:

> Ubuntu 16.04
> GNU Make 4.1
> git version 2.7.4
> PlatformIO, version 2.9.1
> NodeJS v5.11.1

**Comment by seclorum** [comment]
Looks like you have a typo in the Makefile or something -  as there should probably be a \n between that call to pio, which look like two separate calls appended to each other.. 

Should be this:

```
platformio run --target upload --upload-port `pio serialports list --json-output | python -c 'exec("""\nimport json,sys\n\nobj=json.load(sys.stdin)\nfor y in obj:\n if "10C4:EA60" in y["hwid"].upper():\n  print (y["port"])\n""")' | tail -1`
```

.. but ymmv.

**Comment by ffppmm** [comment]
Hi,

its "your" makefile :) from github. Lets make things clearer. In the MS3000-Firmware/MS3KOS/Makefile the target run: states

> run:
>        pio run -p ${MS3000_PORT}

But there is no option -p for pio!

> $ pio -p
> Error: no such option: -p

It looks if they changed the parameters from -p to --upload-port (a little bit strange). Helps?

LG Philipp

**Comment by seclorum** [comment]
Ah, well, here is my side of things

```
$ pio --version
PlatformIO, version 2.9.1
```

Eh, my Makefile looks like this:

```

run:
    platformio run --upload-port ${MS3000_PORT}

```

.. and I've just gotten in the habit of doing 'make clean setup test' as my main build command, which I have bound in SublimeText, just fyi ..

**Comment by ffppmm** [comment]
strange maybe because I removed the

> git submodule foreach git checkout master

Makefile. I'll test this

**Comment by seclorum** [comment]
Well anyway, be forewarned: there are issues with the current xtensa toolchain ..

**Comment by ffppmm** [comment]
No thats not the cause. and my run command is with pio run -p. Maybe some unpushed commits?

**Comment by seclorum** [comment]
Yes, that is the case, I have a local branch I've not yet pushed. Also I have upgraded to PlatformIO 2.9.1 for other projects.  I will push my changes for pio 2.9.1 + MagicShifter soon.

**Comment by ffppmm** [comment]
ty, try to get it compiling and flashing

**Comment by ffppmm** [comment]
OK last question for today. The code for the 1.0 release is not on github?

**Comment by seclorum** [comment]
It is, in master branch ..

**Comment by ffppmm** [comment]
ok I'll test it, ty

**Comment by ffppmm** [comment]
Hi,

got it running, thanks for your help. I had another Problem with the battery, turning the MS off :( not a code problem. I will try my own module now :)

**Comment by seclorum** [comment]
Cool!  I have a PR to submit some time at the end of the week, will fix a few things and add a few things .. definitely interested in what your module does, so hope you'll share details too..

**Comment by ffppmm** [comment]
ofc

**Comment by wizard23** [comment]
@seclorum Is this fixed now?

**Comment by seclorum** [comment]
TODO: confirm fixed.
